# 将静态内容部署到 GitHub Pages 的简单工作流程
名称：将静态内容部署到页面

在：
  #针对默认分支的个体上运动
  推：推：推：推：
    修改：[ “主要” ]

  # 允许您从“操作”选项卡手动运行此工作流程
  活动调度：

# 设置 GITHUB_TOKEN 的权限以允许部署到 GitHub Pages
权限：
  内容：阅读
  页数：写
  基督说：写

# 只允许一次队列配置，跳过队列的运行和最新队列之间的队列运行。
#但是完成后，不要取消发送的运行，因为我们希望这些生产配置能够。
并发性：
  组：“页面”
  取消进行中:true

工作：
  # 由于我们只是部署，因此采用单一部署作业
  部署：
    环境：
      名称： github-pages
      网址： $ {    {步骤.配置.输出.页面网址 }    }
    运行于： ubuntu-latest
    步骤：
      -名称：结帐
        用途：actions/checkout@v3
      -名称：设置页面
        用途： actions/configure-pages@v2
      -名称：上传工件
        用途： actions/upload-pages-artifact@v1
        和：
          # 上传整个仓库
          小路：'.'
      -名称：到配置GitHub Pages
        id：部署
        用途： actions/deploy-pages@v4
